# Generated by Django 5.2.5 on 2025-08-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_preprocesstext_created_at_preprocesstext_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="preprocesstext",
            name="file_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="preprocesstext",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
