# Generated by Django 5.2.5 on 2025-08-09 12:40

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_chathistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="chathistory",
            name="session_id",
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="preprocesstext",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="uploads/",
                validators=[app.models.validate_file_type],
            ),
        ),
    ]
