# Generated by Django 5.2.5 on 2025-08-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_remove_preprocesstext_text_preprocesstext_session_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="preprocesstext",
            name="text",
            field=models.CharField(blank=True, null=True),
        ),
    ]
